spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
      mvc:
        routes:
          - id: "order-service"
            uri: "http://localhost:8081" #UR? DE??L SERV?S ?SM? KULLANMAK
            predicates:
              - "Path=/api/v1/orders/**"
          - id: "customer-service"
            uri: "http://localhost:8083"
            predicates:
              - "Path=/api/v1/customers/**"
          - id: "cart-service"
            uri: "http://localhost:8082"
            predicates:
              - "Path=/api/v1/cart/**"

server:
  port: 8080



#ctrl shift f