spring:
  application:
    name: "gateway-server"
  cloud:
    gateway:
        routes:
          - id: "order-service"
            uri: "lb://order-service" #lb->load-balancing
            predicates:
              - "Path=/api/v1/orders/**"
          - id: "customer-service"
            uri: "lb://customer-service"
            predicates:
              - "Path=/api/v1/customers/**"
          - id: "cart-service"
            uri: "lb://cart-service"
            predicates:
              - "Path=/api/v1/cart/**"
          - id: "product-service"
            uri: "lb://product-service"
            predicates:
              - "Path=/api/v1/products/**"

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true

#ctrl shift f